# Generated by Django 6.0.1 on 2026-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onetimetoken',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
