# Generated by Django 6.0.1 on 2026-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebatch',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
