# Generated by Django 6.0.1 on 2026-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_filebatch_comment_chunkedupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebatch',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True),
        ),
    ]
