# Generated by Django 6.0.1 on 2026-02-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_filebatch_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebatch',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
